version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo install
  pre_build:
    commands:
      - echo pre_build
  build:
    commands:
      - mvn package -DskipTests=true
      - echo build
  post_build:
    commands:
      - echo post_build

artifacts:
  files:
    - target/*.jar
  discard-paths: yes
