version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      curl -sL https://repos.fedoraproject.org/pkgs/maven/maven-3.6.3/maven-3.6.3-1.el7.x86_64.rpm > maven.rpm
      sudo rpm -ivh maven.rpm
      echo Maven installed successfully
  
  build:
    commands:
      mvn clean package -DskipTests=true

  post_build:
    commands:
     cp target/*.jar $CODEBUILD_SRC_DIR/application.jar
  
artifacts:
  base-directory: .
  files:
    - application.jar
  discard-paths: yes
